# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0017_classicrecipe_needs_attention'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerRecipeExtraURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name to display for link', max_length=50)),
                ('url', models.CharField(help_text='Template for URL to link to (macros: %pn% %pv% %branch% %actual_branch%)', max_length=255, verbose_name='URL')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layerindex.LayerItem')),
            ],
            options={'verbose_name': 'Layer Recipe Extra URL'},
        ),
    ]
