# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0018_layerrecipeextraurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layeritem',
            old_name='classic',
            new_name='comparison',
        ),
        migrations.AlterField(
            model_name='layeritem',
            name='comparison',
            field=models.BooleanField(default=False, help_text='Is this a comparison layer?', verbose_name='Comparison'),
        ),
    ]
