# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-13 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0023_layerupdate_layer_branch_finalise'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerupdate',
            name='vcs_after_rev',
            field=models.CharField(blank=True, max_length=80, verbose_name='Revision after'),
        ),
        migrations.AddField(
            model_name='layerupdate',
            name='vcs_before_rev',
            field=models.CharField(blank=True, max_length=80, verbose_name='Revision before'),
        ),
        migrations.AddField(
            model_name='layerupdate',
            name='retcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='layerupdate',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
