# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-18 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0024_layerupdate_vcs_revs'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='retcode',
            field=models.IntegerField(default=0),
        ),
    ]
