# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-05 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0025_update_retcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('layerbranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layerindex.LayerBranch')),
            ],
        ),
    ]
