# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-13 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0026_incfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='apply_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='patch',
            options={'ordering': ['recipe', 'apply_order'], 'verbose_name_plural': 'Patches'},
        ),
    ]
