# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 01:25
from __future__ import unicode_literals

from django.db import migrations
from layerindex.securityquestions import security_questions


def populate_security_questions(apps, schema_editor):
    SecurityQuestion = apps.get_model('layerindex', 'SecurityQuestion')

    for question in security_questions:
        securityquestion = SecurityQuestion()
        securityquestion.question = question
        securityquestion.save()

class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0030_securityquestion'),
    ]

    operations = [
        migrations.RunPython(populate_security_questions),
    ]
