# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-21 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layerindex', '0031_securityquestion_populate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchDisposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition', models.CharField(choices=[('A', 'Apply'), ('R', 'Further review'), ('E', 'Existing'), ('N', 'Not needed'), ('V', 'Different version'), ('I', 'Invalid')], default='A', max_length=1)),
                ('comment', models.TextField(blank=True)),
                ('patch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='layerindex.Patch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('patch_disposition', 'Can disposition patches'),),
            },
        ),
    ]
