# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-01 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0032_patchdisposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='sha256sum',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
