# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0037_patch_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='striplevel',
            field=models.IntegerField(default=1),
        ),
    ]
