# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 21:34
from __future__ import unicode_literals
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('layerindex', '0041_recipe_configopts'),
    ]
    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
