# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-20 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0042_recipe_pe_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='srcrev',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
