# Generated by Django 3.0.14 on 2021-07-18 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0044_extendedprovides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicrecipe',
            name='cover_layerbranch',
            field=models.ForeignKey(blank=True, limit_choices_to={'branch__name': 'master'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layerindex.LayerBranch', verbose_name='Covering layer'),
        ),
    ]
