# Generated by Django 3.2.12 on 2022-04-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0045_layerbranch_classicrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='status',
            field=models.CharField(choices=[('U', 'Unknown'), ('A', 'Accepted'), ('P', 'Pending'), ('I', 'Inappropriate'), ('B', 'Backport'), ('S', 'Submitted'), ('D', 'Denied'), ('N', 'Inactive-Upstream')], default='U', max_length=1),
        ),
    ]
