# Generated by Django 4.2.6 on 2023-10-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0046_alter_patch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerbranch',
            name='updates_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatically updating layer metadata for this layer:branch via the update script', verbose_name='Enable updates'),
        ),
    ]
