# Generated by Django 4.2.9 on 2024-01-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layerindex", "0047_layerbranch_updates_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="BBClassGlobal",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("layerindex.bbclass",),
        ),
        migrations.CreateModel(
            name="BBClassRecipe",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("layerindex.bbclass",),
        ),
        migrations.AddField(
            model_name="bbclass",
            name="bbclass_type",
            field=models.CharField(
                choices=[("", "Class"), ("Global", "Global"), ("Recipe", "Recipe")],
                default="",
                max_length=25,
            ),
        ),
    ]
