# Generated by Django 4.2.9 on 2024-01-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layerindex", "0048_bbclassglobal_bbclassrecipe_bbclass_bbclass_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layerbranch",
            name="vcs_subdir",
            field=models.CharField(
                blank=True,
                help_text="Subdirectory within the repository where the layer is located, if not in the root (usually only used if the repository contains more than one layer)",
                max_length=60,
                verbose_name="Repository subdirectory",
            ),
        ),
    ]
