# Generated by Django 6.1 on 2026-08-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layerindex", "0052_source_path"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bbappend",
            index=models.Index(
                fields=["layerbranch", "filename"], name="bbappend_lb_filename"
            ),
        ),
        migrations.AddIndex(
            model_name="patch",
            index=models.Index(fields=["recipe", "status"], name="patch_recipe_status"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["layerbranch", "pn"], name="recipe_layerbranch_pn"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["pn", "layerbranch"], name="recipe_pn_layerbranch"
            ),
        ),
    ]
