# Generated by Django 6.1 on 2026-08-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layerindex", "0053_add_query_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitenotice",
            name="expires",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Optional date/time when this notice will stop showing",
                null=True,
            ),
        ),
    ]
