# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0016_rmh_layerbranch_nonnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplan',
            name='maintainer_style',
            field=models.CharField(choices=[('I', 'Per-recipe - maintainers.inc'), ('L', 'Layer-wide')], default='L', help_text='Maintainer tracking style for the layers within this plan', max_length=1),
        ),
    ]
