# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0013_patch'),
        ('rrs', '0017_maintenanceplan_maintainer_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemaintainerhistory',
            name='sha1',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='recipemaintainerhistory',
            unique_together=set([('layerbranch', 'sha1')]),
        ),
    ]
