# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-25 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0018_rmh_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceplan',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Plan administrator', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
