# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-26 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0020_recipesymbol_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemaintainer',
            name='recipesymbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrs.RecipeSymbol'),
        ),
        migrations.AlterField(
            model_name='recipeupgrade',
            name='recipesymbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrs.RecipeSymbol'),
        ),
        migrations.AlterField(
            model_name='recipeupstream',
            name='recipesymbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrs.RecipeSymbol'),
        ),
    ]
