# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-26 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0021_recipesymbol_nonnull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemaintainer',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipeupgrade',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipeupstream',
            name='recipe',
        ),
    ]
