# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0022_recipesymbol_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeupgrade',
            name='filepath',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='recipeupgrade',
            name='upgrade_type',
            field=models.CharField(choices=[('U', 'Upgrade'), ('N', 'Delete'), ('R', 'Delete (final)')], db_index=True, default='U', max_length=1),
        ),
    ]
