# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0023_recipeupgrade_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeupgrade',
            name='upgrade_type',
            field=models.CharField(choices=[('U', 'Upgrade'), ('D', 'Downgrade'), ('N', 'Delete'), ('R', 'Delete (final)')], db_index=True, default='U', max_length=1),
        ),
    ]
