# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-19 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0041_recipe_configopts'),
        ('rrs', '0025_recipeupgrade_move'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeUpgradeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Group title', max_length=100)),
                ('recipesymbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrs.RecipeSymbol')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeUpgradeGroupRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(help_text='Regular expression to match recipe to apply to', max_length=100)),
                ('version', models.CharField(help_text='Regular expression to split version component on', max_length=100)),
                ('layerbranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layerindex.LayerBranch')),
            ],
        ),
        migrations.AddField(
            model_name='recipeupgrade',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrs.RecipeUpgradeGroup'),
        ),
    ]
