# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-20 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0026_recipeupgrade_grouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeupgrade',
            name='prev_version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
