# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-23 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0027_recipeupgrade_prev_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeupgrade',
            name='srcrev',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
