# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-31 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0028_recipeupgrade_srcrev'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeupgrade',
            name='license',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipeupgradegrouprule',
            name='license',
            field=models.CharField(blank=True, help_text='Regular expression to split license on', max_length=100),
        ),
        migrations.AddField(
            model_name='recipeupgradegrouprule',
            name='priority',
            field=models.IntegerField(blank=True, help_text='Order to apply rule in (higher first)', null=True),
        ),
        migrations.AlterField(
            model_name='recipeupgradegrouprule',
            name='pn',
            field=models.CharField(blank=True, help_text='Regular expression to match recipe to apply to', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipeupgradegrouprule',
            name='version',
            field=models.CharField(blank=True, help_text='Regular expression to split version component on', max_length=100),
        ),
        migrations.AlterModelOptions(
            name='recipeupgradegrouprule',
            options={'ordering': ['-priority']},
        ),
    ]
