# -*- coding: utf-8 -*-
# Generated by Django 3.2.11 on 2022-01-13 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0029_rrs_license_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeupgrade',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrs.maintainer'),
        ),
    ]
