# Generated by Django 6.1 on 2026-08-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layerindex", "0053_add_query_indexes"),
        ("rrs", "0030_alter_recipeupgrade_maintainer"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recipesymbol",
            index=models.Index(fields=["layerbranch", "pn"], name="recipesymbol_lb_pn"),
        ),
        migrations.AddIndex(
            model_name="recipeupgrade",
            index=models.Index(
                fields=["recipesymbol", "commit_date"], name="recipeupgrade_rs_date"
            ),
        ),
    ]
